name: Test Build Only

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    name: Test Project Compilation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          chmod +x build.sh
          env CFLAGS=-O3 ./build.sh
          du -sh out/* # حجم فایل‌های خروجی را نشان می‌دهد تا مطمئن شوید بیلد موفق بوده
