name: Build and Save Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    name: Build and Upload Artifacts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          chmod +x build.sh
          env CFLAGS=-O3 ./build.sh
          du -sh out/*

      # مرحله جدید برای ذخیره کردن فایل‌های خروجی
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: doompdf-build-output # نام فایلی که دانلود می‌کنید
          path: out/ # مسیر پوشه‌ای که فایل‌های بیلد در آن قرار دارد
