name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # پیشنهاد می‌شود فقط روی برانچ اصلی (main یا master) دیپلوی انجام شود

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # ارتقا به نسخه ۴ برای پایداری بیشتر

      - name: Build Project
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          chmod +x build.sh # اطمینان از اینکه فایل بیلد قابلیت اجرا دارد
          env CFLAGS=-O3 ./build.sh
          du -sh out/*

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b8079ffa92c97010f2a8d759e24cc782
          projectName: doompdf
          directory: out
